services:
  documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: documentation
    hostname: documentation
    command: serve --dev-addr=0.0.0.0:8010 --watch-theme
    restart: unless-stopped
    ports:
      - "8100:8010"
    volumes:
      - ./documentation:/docs:ro
