"""use token since

Revision ID: 57fc1857024e
Revises: 5b6c396ad14f
Create Date: 2025-09-23 20:56:41.479708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57fc1857024e"
down_revision: Union[str, Sequence[str], None] = "5b6c396ad14f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("use_token_since", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "use_token_since")
    # ### end Alembic commands ###
