"""permissions

Revision ID: 5b6c396ad14f
Revises: f70a711816bb
Create Date: 2025-09-18 20:59:28.229235

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b6c396ad14f"
down_revision: Union[str, Sequence[str], None] = "f70a711816bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "permissions",
            postgresql.ARRAY(sa.String()),
            server_default=sa.text("'{CAN_SELF_DELETE}'::text[]"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "permissions")
    # ### end Alembic commands ###
